#C starter file written by R function SS_writestarter
#C rerun model to get more complete formatting in starter.ss_new
#C should work with SS version: 3.24 or earlier
#C file write time: 2020-05-15 12:19:43
#
nhake-wg20.dat #_datfile
nhake-wg20.ctl #_ctlfile
0 #_init_values_src
1 #_run_display_detail
1 #_detailed_age_structure
0 #_checkup
4 #_parmtrace
1 #_cumreport
1 #_prior_like
1 #_soft_bounds
2 #_N_bootstraps
6 #_last_estimation_phase
10 #_MCMCburn
2 #_MCMCthin
0 #_jitter_fraction
-1 #_minyr_sdreport
-2 #_maxyr_sdreport
0 #_N_STD_yrs
1e-04 #_converge_criterion
0 #_retro_yr
1 #_min_age_summary_bio
2 #_depl_basis
1 #_depl_denom_frac
2 #_SPR_basis
2 #_F_report_units
0 #_F_report_basis
#
999 #_final
