#!/bin/bash

GZFILES=("Report.sso" "covar.sso" "wtatage.ss_new" "CompReport.sso")
KEEPFILES=("warning.sso" "Forecast-report.sso" "starter.ss" "forecast.ss")
INPUTFILES=`find . \( -name "*.dat" -or -name "*.ctl" \) -exec basename {} ';'`
GZEDFILES=("Report.sso.gz" "covar.sso.gz" "wtatage.ss_new.gz" "CompReport.sso.gz")
EXCEPT=("${INPUTFILES[@]}" "${KEEPFILES[@]}" "${GZEDFILES[@]}")

for gzfile in ${GZFILES[@]} 
do
  gzip $gzfile 
done

ALLFILES=`ls -1`

rm `echo ${EXCEPT[@]} ${EXCEPT[@]} ${ALLFILES[@]} | tr ' ' '\n' | sort | uniq -u`
